default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: postgresql

development:
  <<: *default
  database: <%=ENV['DB_NAME']%>
  user: <%=ENV['DB_USER']%>
  password: <%=ENV['DB_PASSWORD']%>

test:
  <<: *default
  database: <%=ENV['DB_NAME_TEST']%>
  user: <%=ENV['DB_USER_TEST']%>
  password: <%=ENV['DB_PASSWORD_TEST']%>
